twig:
    file_name_pattern: '*.twig'
<<<<<<< HEAD
=======
    form_themes:
        - 'bootstrap_5_layout.html.twig'
>>>>>>> 2e5d736b7c09004bb95e82e33ea9ef850dfb84eb

when@test:
    twig:
        strict_variables: true
