<?php

namespace ContainerEzgTaIa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R6D0ZVBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R6D0ZVB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AgriculteurController::diagnosticDetail' => ['privates', '.service_locator.cBcs01K', 'get_ServiceLocator_CBcs01KService', true],
            'App\\Controller\\AgriculteurController::diagnostics' => ['privates', '.service_locator.Ns.uOPO', 'get_ServiceLocator_Ns_UOPOService', true],
            'App\\Controller\\AgriculteurController::home' => ['privates', '.service_locator.iWYALUj', 'get_ServiceLocator_IWYALUjService', true],
            'App\\Controller\\AgriculteurController::irrigation' => ['privates', '.service_locator.aBMdRUC', 'get_ServiceLocator_ABMdRUCService', true],
            'App\\Controller\\AgriculteurController::irrigationDetail' => ['privates', '.service_locator.iWYALUj', 'get_ServiceLocator_IWYALUjService', true],
            'App\\Controller\\AgriculteurController::nouveauDiagnostic' => ['privates', '.service_locator.oHviBMb', 'get_ServiceLocator_OHviBMbService', true],
            'App\\Controller\\CultureController::delete' => ['privates', '.service_locator._p8RGqx', 'get_ServiceLocator_P8RGqxService', true],
            'App\\Controller\\CultureController::edit' => ['privates', '.service_locator._p8RGqx', 'get_ServiceLocator_P8RGqxService', true],
            'App\\Controller\\CultureController::index' => ['privates', '.service_locator.NHgkJUS', 'get_ServiceLocator_NHgkJUSService', true],
            'App\\Controller\\CultureController::new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ExpertController::diagnostics' => ['privates', '.service_locator.Ns.uOPO', 'get_ServiceLocator_Ns_UOPOService', true],
            'App\\Controller\\ExpertController::home' => ['privates', '.service_locator.v2CAKzS', 'get_ServiceLocator_V2CAKzSService', true],
            'App\\Controller\\ExpertController::irrigation' => ['privates', '.service_locator.aBMdRUC', 'get_ServiceLocator_ABMdRUCService', true],
            'App\\Controller\\ExpertController::irrigationDetail' => ['privates', '.service_locator.if.MNfg', 'get_ServiceLocator_If_MNfgService', true],
            'App\\Controller\\ExpertController::irrigationSave' => ['privates', '.service_locator.xHXTAck', 'get_ServiceLocator_XHXTAckService', true],
            'App\\Controller\\ExpertController::nouveauProduit' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ExpertController::produits' => ['privates', '.service_locator.XlJjyAP', 'get_ServiceLocator_XlJjyAPService', true],
            'App\\Controller\\ExpertController::repondre' => ['privates', '.service_locator.woQOiIH', 'get_ServiceLocator_WoQOiIHService', true],
            'App\\Controller\\ExpertController::supprimerProduit' => ['privates', '.service_locator.Rbwe524', 'get_ServiceLocator_Rbwe524Service', true],
            'App\\Controller\\PlanIrrigationController::approuver' => ['privates', '.service_locator.cMg95c9', 'get_ServiceLocator_CMg95c9Service', true],
            'App\\Controller\\PlanIrrigationController::delete' => ['privates', '.service_locator.cMg95c9', 'get_ServiceLocator_CMg95c9Service', true],
            'App\\Controller\\PlanIrrigationController::index' => ['privates', '.service_locator.aBMdRUC', 'get_ServiceLocator_ABMdRUCService', true],
            'App\\Controller\\PlanIrrigationController::new' => ['privates', '.service_locator.oHviBMb', 'get_ServiceLocator_OHviBMbService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AgriculteurController:diagnosticDetail' => ['privates', '.service_locator.cBcs01K', 'get_ServiceLocator_CBcs01KService', true],
            'App\\Controller\\AgriculteurController:diagnostics' => ['privates', '.service_locator.Ns.uOPO', 'get_ServiceLocator_Ns_UOPOService', true],
            'App\\Controller\\AgriculteurController:home' => ['privates', '.service_locator.iWYALUj', 'get_ServiceLocator_IWYALUjService', true],
            'App\\Controller\\AgriculteurController:irrigation' => ['privates', '.service_locator.aBMdRUC', 'get_ServiceLocator_ABMdRUCService', true],
            'App\\Controller\\AgriculteurController:irrigationDetail' => ['privates', '.service_locator.iWYALUj', 'get_ServiceLocator_IWYALUjService', true],
            'App\\Controller\\AgriculteurController:nouveauDiagnostic' => ['privates', '.service_locator.oHviBMb', 'get_ServiceLocator_OHviBMbService', true],
            'App\\Controller\\CultureController:delete' => ['privates', '.service_locator._p8RGqx', 'get_ServiceLocator_P8RGqxService', true],
            'App\\Controller\\CultureController:edit' => ['privates', '.service_locator._p8RGqx', 'get_ServiceLocator_P8RGqxService', true],
            'App\\Controller\\CultureController:index' => ['privates', '.service_locator.NHgkJUS', 'get_ServiceLocator_NHgkJUSService', true],
            'App\\Controller\\CultureController:new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ExpertController:diagnostics' => ['privates', '.service_locator.Ns.uOPO', 'get_ServiceLocator_Ns_UOPOService', true],
            'App\\Controller\\ExpertController:home' => ['privates', '.service_locator.v2CAKzS', 'get_ServiceLocator_V2CAKzSService', true],
            'App\\Controller\\ExpertController:irrigation' => ['privates', '.service_locator.aBMdRUC', 'get_ServiceLocator_ABMdRUCService', true],
            'App\\Controller\\ExpertController:irrigationDetail' => ['privates', '.service_locator.if.MNfg', 'get_ServiceLocator_If_MNfgService', true],
            'App\\Controller\\ExpertController:irrigationSave' => ['privates', '.service_locator.xHXTAck', 'get_ServiceLocator_XHXTAckService', true],
            'App\\Controller\\ExpertController:nouveauProduit' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ExpertController:produits' => ['privates', '.service_locator.XlJjyAP', 'get_ServiceLocator_XlJjyAPService', true],
            'App\\Controller\\ExpertController:repondre' => ['privates', '.service_locator.woQOiIH', 'get_ServiceLocator_WoQOiIHService', true],
            'App\\Controller\\ExpertController:supprimerProduit' => ['privates', '.service_locator.Rbwe524', 'get_ServiceLocator_Rbwe524Service', true],
            'App\\Controller\\PlanIrrigationController:approuver' => ['privates', '.service_locator.cMg95c9', 'get_ServiceLocator_CMg95c9Service', true],
            'App\\Controller\\PlanIrrigationController:delete' => ['privates', '.service_locator.cMg95c9', 'get_ServiceLocator_CMg95c9Service', true],
            'App\\Controller\\PlanIrrigationController:index' => ['privates', '.service_locator.aBMdRUC', 'get_ServiceLocator_ABMdRUCService', true],
            'App\\Controller\\PlanIrrigationController:new' => ['privates', '.service_locator.oHviBMb', 'get_ServiceLocator_OHviBMbService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AgriculteurController::diagnosticDetail' => '?',
            'App\\Controller\\AgriculteurController::diagnostics' => '?',
            'App\\Controller\\AgriculteurController::home' => '?',
            'App\\Controller\\AgriculteurController::irrigation' => '?',
            'App\\Controller\\AgriculteurController::irrigationDetail' => '?',
            'App\\Controller\\AgriculteurController::nouveauDiagnostic' => '?',
            'App\\Controller\\CultureController::delete' => '?',
            'App\\Controller\\CultureController::edit' => '?',
            'App\\Controller\\CultureController::index' => '?',
            'App\\Controller\\CultureController::new' => '?',
            'App\\Controller\\ExpertController::diagnostics' => '?',
            'App\\Controller\\ExpertController::home' => '?',
            'App\\Controller\\ExpertController::irrigation' => '?',
            'App\\Controller\\ExpertController::irrigationDetail' => '?',
            'App\\Controller\\ExpertController::irrigationSave' => '?',
            'App\\Controller\\ExpertController::nouveauProduit' => '?',
            'App\\Controller\\ExpertController::produits' => '?',
            'App\\Controller\\ExpertController::repondre' => '?',
            'App\\Controller\\ExpertController::supprimerProduit' => '?',
            'App\\Controller\\PlanIrrigationController::approuver' => '?',
            'App\\Controller\\PlanIrrigationController::delete' => '?',
            'App\\Controller\\PlanIrrigationController::index' => '?',
            'App\\Controller\\PlanIrrigationController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AgriculteurController:diagnosticDetail' => '?',
            'App\\Controller\\AgriculteurController:diagnostics' => '?',
            'App\\Controller\\AgriculteurController:home' => '?',
            'App\\Controller\\AgriculteurController:irrigation' => '?',
            'App\\Controller\\AgriculteurController:irrigationDetail' => '?',
            'App\\Controller\\AgriculteurController:nouveauDiagnostic' => '?',
            'App\\Controller\\CultureController:delete' => '?',
            'App\\Controller\\CultureController:edit' => '?',
            'App\\Controller\\CultureController:index' => '?',
            'App\\Controller\\CultureController:new' => '?',
            'App\\Controller\\ExpertController:diagnostics' => '?',
            'App\\Controller\\ExpertController:home' => '?',
            'App\\Controller\\ExpertController:irrigation' => '?',
            'App\\Controller\\ExpertController:irrigationDetail' => '?',
            'App\\Controller\\ExpertController:irrigationSave' => '?',
            'App\\Controller\\ExpertController:nouveauProduit' => '?',
            'App\\Controller\\ExpertController:produits' => '?',
            'App\\Controller\\ExpertController:repondre' => '?',
            'App\\Controller\\ExpertController:supprimerProduit' => '?',
            'App\\Controller\\PlanIrrigationController:approuver' => '?',
            'App\\Controller\\PlanIrrigationController:delete' => '?',
            'App\\Controller\\PlanIrrigationController:index' => '?',
            'App\\Controller\\PlanIrrigationController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);

        if (isset($container->privates['.service_locator.R6D0ZVB'])) {
            return $container->privates['.service_locator.R6D0ZVB'];
        }

        return $container->privates['.service_locator.R6D0ZVB'] = $instance;
    }
}
