<?php

namespace ContainerEzgTaIa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WoQOiIHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.woQOiIH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\DiagnosticRepository', 'getDiagnosticRepositoryService', true],
        ], [
            'em' => '?',
            'repo' => 'App\\Repository\\DiagnosticRepository',
        ]);

        if (isset($container->privates['.service_locator.woQOiIH'])) {
            return $container->privates['.service_locator.woQOiIH'];
        }

        return $container->privates['.service_locator.woQOiIH'] = $instance;
    }
}
