<?php

namespace ContainerEzgTaIa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P8RGqxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._p8RGqx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'culture' => ['privates', '.errored..service_locator._p8RGqx.App\\Entity\\Culture', NULL, 'Cannot autowire service ".service_locator._p8RGqx": it needs an instance of "App\\Entity\\Culture" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'culture' => 'App\\Entity\\Culture',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator._p8RGqx'])) {
            return $container->privates['.service_locator._p8RGqx'];
        }

        return $container->privates['.service_locator._p8RGqx'] = $instance;
    }
}
