<?php

namespace ContainerEzgTaIa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rbwe524Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Rbwe524' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'produit' => ['privates', '.errored..service_locator.Rbwe524.App\\Entity\\ProduitPhytosanitaire', NULL, 'Cannot autowire service ".service_locator.Rbwe524": it needs an instance of "App\\Entity\\ProduitPhytosanitaire" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'produit' => 'App\\Entity\\ProduitPhytosanitaire',
        ]);

        if (isset($container->privates['.service_locator.Rbwe524'])) {
            return $container->privates['.service_locator.Rbwe524'];
        }

        return $container->privates['.service_locator.Rbwe524'] = $instance;
    }
}
