<?php

namespace ContainerEzgTaIa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OHviBMbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oHviBMb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cultureRepo' => ['privates', 'App\\Repository\\CultureRepository', 'getCultureRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'cultureRepo' => 'App\\Repository\\CultureRepository',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.oHviBMb'])) {
            return $container->privates['.service_locator.oHviBMb'];
        }

        return $container->privates['.service_locator.oHviBMb'] = $instance;
    }
}
