<?php

namespace ContainerEzgTaIa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XlJjyAPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XlJjyAP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XlJjyAP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\ProduitPhytosanitaireRepository', 'getProduitPhytosanitaireRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\ProduitPhytosanitaireRepository',
        ]);
    }
}
