<?php

namespace ContainerEzgTaIa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V2CAKzSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v2CAKzS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v2CAKzS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'diagRepo' => ['privates', 'App\\Repository\\DiagnosticRepository', 'getDiagnosticRepositoryService', true],
            'produitRepo' => ['privates', 'App\\Repository\\ProduitPhytosanitaireRepository', 'getProduitPhytosanitaireRepositoryService', true],
        ], [
            'diagRepo' => 'App\\Repository\\DiagnosticRepository',
            'produitRepo' => 'App\\Repository\\ProduitPhytosanitaireRepository',
        ]);
    }
}
