<?php

namespace ContainerEzgTaIa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCultureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._p8RGqx.App\Entity\Culture' shared service.
     *
     * @return \App\Entity\Culture
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._p8RGqx": it needs an instance of "App\\Entity\\Culture" but this type has been excluded in "config/services.yaml".');
    }
}
