<?php

namespace ContainerEzgTaIa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDiagnosticService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cBcs01K.App\Entity\Diagnostic' shared service.
     *
     * @return \App\Entity\Diagnostic
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cBcs01K": it needs an instance of "App\\Entity\\Diagnostic" but this type has been excluded in "config/services.yaml".');
    }
}
