<?php

namespace ContainerEzgTaIa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitPhytosanitaireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Rbwe524.App\Entity\ProduitPhytosanitaire' shared service.
     *
     * @return \App\Entity\ProduitPhytosanitaire
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Rbwe524": it needs an instance of "App\\Entity\\ProduitPhytosanitaire" but this type has been excluded in "config/services.yaml".');
    }
}
