<?php

namespace ContainerEzgTaIa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlanIrrigationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cMg95c9.App\Entity\PlanIrrigation' shared service.
     *
     * @return \App\Entity\PlanIrrigation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cMg95c9": it needs an instance of "App\\Entity\\PlanIrrigation" but this type has been excluded in "config/services.yaml".');
    }
}
