<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEzgTaIa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEzgTaIa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEzgTaIa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEzgTaIa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEzgTaIa\App_KernelDevDebugContainer([
    'container.build_hash' => 'EzgTaIa',
    'container.build_id' => 'd0724c2d',
    'container.build_time' => 1775763215,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEzgTaIa');
